language: ruby
cache: bundler

gemfile:
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile

rvm:
  - "2.2.7"
  - "2.3.4"

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - adam.meehan@gmail.com
    on_failure: change
    on_success: never
