language: ruby
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
before_script:
  - bundle install
cache: bundler

gemfile:
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile

rvm:
  - "2.3.7"
  - "2.4.4"
  - "2.5.5"

script: 'bundle exec rspec'

notifications:
  email:
    recipients:
      - adam.meehan@gmail.com
    on_failure: change
    on_success: never
