name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - gemfile: rails_6_0
            ruby: 2.6
          - gemfile: rails_6_0
            ruby: 2.7
          - gemfile: rails_6_0
            ruby: 3.0
          - gemfile: rails_6_1
            ruby: 2.6
          - gemfile: rails_6_1
            ruby: 2.7
          - gemfile: rails_6_1
            ruby: 3.0

    name: ${{ matrix.gemfile }}, ruby ${{ matrix.ruby }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: false

    - name: Bundle install
      run: |
        bundle config set gemfile "${GITHUB_WORKSPACE}/gemfiles/${{ matrix.gemfile }}.gemfile"
        bundle install --jobs 4 --retry 3

    - name: Run specs
      run: |
        bundle exec rspec
